# Generated by Django 4.2.4 on 2023-08-31 12:09

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0003_alter_userbranch_user'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userbranch',
            name='branch',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='branch', to='users.branch', verbose_name='Branch'),
        ),
    ]
